server:
  port: 9000
spring:
  profiles:
    include: sharding  #包含的文件不用区分激活的profile
  #  profiles:
#    active: sharding,dev # application-{profile}.yaml 同时激活
#  zipkin:
#    base-url: http://192.168.6.100:9411/
#    sender:
#      type: web
  datasource:
    url: jdbc:mysql://192.168.6.100:3306/gmall_product?useSSL=false&characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
#  redis:
#    host: 192.168.6.100
#    password: Lfy123456
app:
  minio:
    endpoint: http://192.168.6.100:9000
    ak: admin
    sk: admin123456
    bucketName: gmall
  thread-pool:
    core: 4
    max: 8
